### ISSUE TITLE
Impossible to change the alignement of the label in text button 

### ISSUE THREAD

**Issue by leeserlionel** [AJARProject/AJUI_Button#2]
**Describe the bug**
The bug can be reproduced in the AJUI_Button Lab.

Changing the property "textAlign" of a text button does nothing. And actually in a other base when I create a button and try to change the property like this : 

`Form.btn1.TextAlign(AJUI_btn_default; "left")`

It throws an error : A member 'function' is expected

The documentation (French and English) make absolutely no references of this property, only of compTextAlign that does not work either for text buttons.

**To Reproduce**
1. Open AJUI_Button Lab
2. Change the property "textAlign" in a text button

**Current behavior**
Nothing

**Expected behavior**
Label align itself to the left or the right

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.7
 - 4D v18 R5.258326

**Comment by Ganbin** [comment]
Hi Thanks you for the report.

This feature is actually missing and we will provide it as soon as possible

It will come with the possibility to set the padding of the button.

**Comment by Ganbin** [comment]
You can find the release including the text align and the padding for text button : [Release 1.5.0](https://github.com/AJARProject/AJUI_Button/releases/tag/1.5.0)

Let me know if this fix your issue.

**Comment by leeserlionel** [comment]
Thanks Gabriel,

But how to set it ?

`Form.btn1.TextAlign(AJUI_btn_default; "left")`

or

`Form.btn1.textAlign:="left"`

both doesn't work.

I'm probably missing something.

**Comment by Ganbin** [comment]
I have implement it that way 

`form.btn.textAlign(AJUI_btn_default; "left")`

Why I have done this way?

I am preparing a v2.0.0 where I will change most of the formula to be more simple. I will also change that they start with lowerCase.

The purpose is to make all the AJUI components to use the same formula, today some are using different way to achieve the same thing.

As I don't have much time I try to do it when I have time. I have already did it for AJUI_ProgressBar.

**Comment by leeserlionel** [comment]
Alright now everything is working well ! 

Ok this is a big change, better do it before a lot of people use the component.

Thanks for the informations it’s an amazing component.



Lionel
